name: DeathCoordinate
main: com.Feshior.DeathCoordinate.DeathCoordinate
version: 2.0
author: Feshior
api-version: 1.17
commands:
  getDeaths:
    description: Command that return all player deaths coordinates
    usage: /getDeaths